### ISSUE TITLE
Error while trying to install via Wabbajack

### ISSUE THREAD

**Issue by Gilsh2019** [Ashok0/EnderalVREssentials-Nightly#1]
I keep getting the following error while trying to install via wabbajack. I followed the instructions to the letter but still get it. Please can you help me solve this. I have attached a screenshot of the issue

<img width="1004" alt="Capture" src="https://user-images.githubusercontent.com/120559307/207557512-98d49c4b-2cc3-4796-a706-0662190cbf10.PNG">
<img width="1004" alt="Capture" src="https://user-images.githubusercontent.com/120559307/207557732-790b1d52-6432-41e3-8178-85cee8546823.PNG">

![image](https://user-images.githubusercontent.com/120559307/207557689-d13da9d5-f541-48ed-8d70-27ffc10f44f1.png)

**Comment by Gilsh2019** [comment]
![image](https://user-images.githubusercontent.com/120559307/207612809-3a1b487b-51f7-4f85-86ba-f17640452955.png)

![image](https://user-images.githubusercontent.com/120559307/207612915-6f34f27c-57ff-4c3b-bebe-716dd9cb3cab.png)

**Comment by Gilsh2019** [comment]
![image](https://user-images.githubusercontent.com/120559307/207613222-d1f8d1a9-91e8-4e9c-8a88-4112b575b50b.png)

**Comment by Ashok0** [comment]
Hi, I tried installing the Wabbajack and received the same error regarding "\Extractors\windows-x64\7z.exe".  It seems to always happen when you double-click the .wabbajack file to initiate the install.  

To get around this error, launch Wabbajack and then select Install from Disk.  Next, manually select the .wabbajack file under "Target Modlist" and select your installation location under "Modlist Installation Location".  Tick "Overwrite Installation" if you are updating a previous installation and hit Run, and Enderal VR should install without any errors.

**Comment by Gilsh2019** [comment]
This worked, thank you so much and also for all the work and effort you
have put into this
