### ISSUE TITLE
Getting floating heads and arms

### ISSUE THREAD

**Issue by danielsobrado** [Ashok0/EnderalVREssentials-Nightly#2]
The body of the NPCs doesn't appear for me, only the heads and arms, any suggestion?

**Comment by Ashok0** [comment]
Hi, make sure to perform the Somnium setup which resolves the invisible body issue.  https://github.com/Ashok0/EnderalVREssentials-Nightly#somnium-setup

If you have trouble installing the Somnium Wabbajack, email me at ashok0@gmail.com and I will provide you with the required Somnium asset files which I do not have permission to redistribute publicly.
